; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = esp32dev ; <--- Thêm dòng này để mặc định chọn môi trường đúng

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
;monitor_speed = 9600

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Tốc độ upload code và xem log
monitor_speed = 115200
upload_speed = 921600

; --- KHAI BÁO THƯ VIỆN Ở ĐÂY ---
lib_deps =
    knolleary/PubSubClient @ ^2.8
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306